// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessage(arg1) {
  return window['go']['main']['App']['AddMessage'](arg1);
}

export function AnalyzePath(arg1) {
  return window['go']['main']['App']['AnalyzePath'](arg1);
}

export function AnalyzePathContent(arg1) {
  return window['go']['main']['App']['AnalyzePathContent'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportChat(arg1) {
  return window['go']['main']['App']['ExportChat'](arg1);
}

export function GetCachedModels(arg1) {
  return window['go']['main']['App']['GetCachedModels'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProvider(arg1) {
  return window['go']['main']['App']['GetProvider'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasAPIKey(arg1) {
  return window['go']['main']['App']['HasAPIKey'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviderModels(arg1) {
  return window['go']['main']['App']['ListProviderModels'](arg1);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function SaveProjectFiles(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectFiles'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendMessageStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessageStream'](arg1, arg2, arg3);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetProjectMeta(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProjectMeta'](arg1, arg2, arg3);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function ValidateProviderKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateProviderKey'](arg1, arg2);
}
