// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {providers} from '../models';
import {settings} from '../models';
import {templates} from '../models';

export function AddMessage(arg1:history.Message):Promise<void>;

export function CreateProject(arg1:history.Project):Promise<void>;

export function ExportChat(arg1:Array<history.Message>):Promise<string>;

export function GetMessages(arg1:string):Promise<Array<history.Message>>;

export function GetProject(arg1:string):Promise<history.Project>;

export function GetProvider(arg1:string):Promise<providers.LLMProvider>;

export function GetSettings():Promise<settings.Config>;

export function Greet(arg1:string):Promise<string>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function ListProjects():Promise<Array<history.Project>>;

export function ListProviderModels(arg1:string):Promise<Array<providers.Model>>;

export function SaveProjectFiles(arg1:string,arg2:templates.ProjectFiles):Promise<void>;

export function SaveSettings(arg1:settings.Config):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<providers.Message>):Promise<providers.ChatResponse>;

export function SendMessageStream(arg1:string,arg2:string,arg3:Array<providers.Message>):Promise<void>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function UpdateProject(arg1:history.Project):Promise<void>;

export function ValidateProviderKey(arg1:string,arg2:string):Promise<void>;
